# Generated by Django 6.0 on 2025-12-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-PESA'), ('cash', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('deposit_paid_date', models.DateTimeField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_paid', models.BooleanField(default=False)),
                ('balance_payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-PESA'), ('cash', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('balance_paid_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
